
spring:
  datasource:
    url: jdbc:mysql://localhost:3307/batch_test
    username: gusdn
    password: thisisTEST!@#
    driver-class-name: com.mysql.cj.jdbc.Driver
  batch:
    job:
      names: ${job.name:NONE}

server:
  port: 8081

---

