spring:
  h2:
    console:
      enabled: true
  jpa:
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:mysql://localhost:3307/book_manager
    username: root
    password: dkahffk11
#    initialization-mode: always
  sql:
    init:
      mode: always
server:
  port: 8070
logging:
  level:
    root: trace


